; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using MEGA.
[ MEGAinfo ]
ver                          = 10210209-x86_64 macOS       
[ DataSettings ]
datatype                     = snTree                      
[ ProcessTypes ]
ppRelTimeBLens               = true                        
[ AnalysisSettings ]
Analysis                     = Estimate Divergence Times (Branch Lengths)
Tree to Use                  = Use tree from file          
Reltime Settings             = ====================        
Max Relative Rate Ratio      = 20                          
Has Time Limit               = False                       
Maximum Execution Time       = -1                          
